import {
    PencilRuler,
    Merge,
    Scissors,
    Zap,
    Wrench,
    ImagePlus,
    PenTool,
    Crop,
    Ungroup,
    Files,
    Trash2,
    Bookmark,
    List,
    ListOrdered,
    Droplets,
    Pilcrow,
    Contrast,
    Palette,
    Type,
    Stamp,
    Eraser,
    SquarePen,
    FileInput,
    FileMinus2,
    Images,
    Image as ImageIcon,
    Smartphone,
    Layers,
    FilePen,
    FileCode,
    FileImage,
    FileText,
    ScanText,
    Shuffle,
    Paperclip,
    Download,
    FileEdit,
    Columns,
    FilePlus2,
    ArrowDownZA,
    RotateCw,
    LayoutGrid,
    UnfoldVertical,
    Info,
    FileCog,
    StretchHorizontal,
    GitCompare,
    NotepadTextDashed,
    Ruler,
    Gauge,
    Unlink,
    Lock,
    ShieldCheck,
    Brush,
    Key,
    FileKey,
    FileLock,
    LucideIcon,
    // 新增文件格式图标
    FileSpreadsheet,
    Presentation,
    FileBox,
    FileType2,
    BookOpen,
    BookMarked,
    RefreshCcw,
    ImageDown,
    Table,
    LayoutDashboard,
    TabletSmartphone
} from 'lucide-react';

export const ICON_MAP: Record<string, LucideIcon> = {
    'pencil-ruler': PencilRuler,
    'combine': Merge,
    'merge': Merge,
    'scissors': Scissors,
    'zap': Zap,
    'pocket-knife': Wrench,
    'image-up': ImagePlus,
    'pen-tool': PenTool,
    'crop': Crop,
    'ungroup': Ungroup,
    'files': Files,
    'trash-2': Trash2,
    'bookmark': Bookmark,
    'list': List,
    'list-ordered': ListOrdered,
    'droplets': Droplets,
    'pilcrow': Pilcrow,
    'contrast': Contrast,
    'palette': Palette,
    'type': Type,
    'stamp': Stamp,
    'eraser': Eraser,
    'square-pen': SquarePen,
    'file-input': FileInput,
    'file-minus-2': FileMinus2,
    'images': Images,
    'image': ImageIcon,
    'smartphone': Smartphone,
    'layers': Layers,
    'file-pen': FilePen,
    'file-code': FileCode,
    'file-image': FileImage,
    'file-text': FileText,
    'scan-text': ScanText,
    'shuffle': Shuffle,
    'paperclip': Paperclip,
    'download': Download,
    'file-edit': FileEdit,
    'table-columns-split': Columns,
    'file-plus-2': FilePlus2,
    'arrow-down-z-a': ArrowDownZA,
    'rotate-cw': RotateCw,
    'layout-grid': LayoutGrid,
    'unfold-vertical': UnfoldVertical,
    'info': Info,
    'file-cog': FileCog,
    'stretch-horizontal': StretchHorizontal,
    'git-compare': GitCompare,
    'notepad-text-dashed': NotepadTextDashed,
    'ruler-dimension-line': Ruler,
    'ruler': Ruler,
    'gauge': Gauge,
    'unlink': Unlink,
    'wrench': Wrench,
    'lock': Lock,
    'brush-cleaning': Brush,
    'shield-check': ShieldCheck,
    'key': Key,
    'file-key': FileKey,
    'file-lock': FileLock,
    // 文件格式专用图标
    'file-spreadsheet': FileSpreadsheet,
    'presentation': Presentation,
    'file-box': FileBox,
    'file-type': FileType2,
    'book-open': BookOpen,
    'book-marked': BookMarked,
    'refresh-ccw': RefreshCcw,
    'image-down': ImageDown,
    'table': Table,
    'layout-dashboard': LayoutDashboard,
    'tablet-smartphone': TabletSmartphone
};

export const getToolIcon = (iconName: string): LucideIcon => {
    return ICON_MAP[iconName] || FileText;
};
